### ISSUE TITLE
Just a sugguestion

### ISSUE THREAD

**Issue by RYNO8** [Dhruv-A/Robotics-Club-Website#2]
Hey Dhruv, I feel that for a Robotics Club website, it would be both easiser and more efficient to use something high level (e.g. Wix, Weebly). This way, we would not be editing html, css and the like. It would be less work this way, although it is slightly less customisable.

**Comment by Jinzato** [comment]
All part of the learning process

**Comment by halcyonhunter** [comment]
I think the point is that the website itself is a project that the club creates.
